vich_uploader:
    db_driver: orm
    mappings:
        category_photo:
            uri_prefix: /images/upload/category
            upload_destination: '%kernel.project_dir%/public/images/upload/category'
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        article_photo:
            uri_prefix: /images/upload/articles
            upload_destination: '%kernel.project_dir%/public/images/upload/articles'
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        article_banniere_photo:
            uri_prefix: /images/upload/articles/banniere
            upload_destination: '%kernel.project_dir%/public/images/upload/articles/banniere'
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
